FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Dev Connect 

Dev Connect is a simple API allowing users to connect with fellow developers

## Add a new user [/register]

### Register a new user [POST]

+ Response 200 (application/json)

        
            {
                "name": "Olowu",
                "email": "bee@gmail.com",
                "password": "bee"
            }