FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Dev Connect 

Dev Connect is a simple API allowing users to connect with fellow developers

## Add a new user [/register]

### Register a new user [POST]

+ Response 200 (application/json)
+ Response 400 (application/json)

## Log in a registered user [/login]

### Log in a registered user [POST]

+ Response 200 (application/json)
+ Response 400 (application/json)

## View logged in user [/user]

### View logged in user [GET]

+ Response 200 (application/json)
+ Response 400 (application/json)